version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: typera-express
    versions:
    - 2.0.0
    - 2.1.0
    - 2.2.0
    - 2.2.1
    - 2.3.0
